### ISSUE TITLE
Add-ZertoPeerSite - Error using hostname

### ISSUE THREAD

**Issue by NScuola** [ZertoPublic/ZertoApiWrapper#103]
## Expected Behavior
When using the Add-ZertoPeerSite module, I'm attempting to use the -targetHost parameter with a hostname instead of an IP address

## Current Behavior
Receiving the following error: Add-ZertoPeerSite: Cannot validate argument on parameter 'targetHost'. Cannot convert value "hostname" to type "System.Net.IPAddress". Error: "An invalid IP address was specified."

## Possible Solution
Line 9 appears to look for an IP Address match. This should also look for hostname input.

## Steps to Reproduce (for bugs)
Use a hostname for the -targetHost parameter when executing the Add-ZertoPeerSite module.

## Context
Had to modify my scripts to use IP addresses only instead of hostnames. 

## Your Environment
* Module version used: 1.4.3
* Operating System and PowerShell version: Windows 10, PowerShell 7.0.3
* Zerto Virtual Manager Version: 8.0 U2

**Comment by wcarroll** [comment]
Looks to be a parameter validation issue. Will look into it.
