### ISSUE TITLE
New-ZertoVPG does not work when replicating to same site

### ISSUE THREAD

**Issue by sleeuwenhoek** [ZertoPublic/ZertoApiWrapper#112]
New-ZertoVPG does not work when replicating to same site

## Expected Behavior
New VPG is created

## Current Behavior
Error because Get-ZertoPeerSite does not show local Site/has as an option for local site

## Possible Solution
Adjust Get-ZertoPeerSite to include local site
Add option to New-ZertoVPG to use local site

## Steps to Reproduce (for bugs)
Create new VPG with a target to another cluster in the same site

## Context
Had to create VPG manually and use Copy-ZertoVPG for subsequent VPGs

## Your Environment
* Module version used: 1.5.1
* Operating System and PowerShell version: Windows Server 2019 PS PS5.1
* Zerto Virtual Manager Version: 8.0U2

**Comment by wcarroll** [comment]
Hi @sleeuwenhoek 

Thanks for bringing this to my attention. I'll dig in and see what I can do to get this updated.

Thanks.

**Comment by wcarroll** [comment]
@sleeuwenhoek ,

I was able to find a method that will make minimal changes to the workflow but will allow for local replication to be set up. This fix is present PR #113 and should get rolled out to the powershell gallery Mondayish of next week. I have a few other fixes I want to include in the update.

Thanks.
