### ISSUE TITLE
start-zertoclonevpg

### ISSUE THREAD

**Issue by vmikemast** [ZertoPublic/ZertoApiWrapper#50]
start-zertoclonevpg

Is there a way to call multiple VPG's using this function?  I have tried a few different options, like comma,  brackets, quotes, etc.   I figured maybe I would have to build an array and modify the ps1 to accept the array. Before I went thru that, I figured I would ask and make sure I am not calling them correctly.

Mike

**Comment by wcarroll** [comment]
Hi Mike,

Currently the `Start-ZertoCloneVpg` function does not support multiple VPGs passed into a single call. The main reason for this is the additional data that can be passed into the function such as Checkpoint ID and specific Virtual Machines would not be the same across multiple VPGs. Having a bit of an understanding as to what you are attempting to accomplish, I might look at creating an array with a list of VPGs and a `foreach` loop to cycle through each VPG and call the function. Something like this:

```PowerShell
$VPGsToClone = @('Vpg1', 'Vpg2', 'Vpg3')
foreach ($Vpg in $VPGsToClone) {
    Start-ZertoCloneVpg -VpgName $Vpg
}
```

Let me know if you have any follow up questions.

Thanks,
Wes

**Comment by vmikemast** [comment]
Thanks Wes.   Wanting to batch clone VPG's to AWS using the latest checkpoint available, for a DR simulation..  setting up for operations team to run the script to recover a batch of VPG's at a time, then once those are complete to kick off another batch. And not have to login to GUI and click each one manually.  
I did setup the array as you shown and did some tweaking on the credentials,  So now they jun the new script in pass in the username and password as parameters and it run the batch of predefined clones that are setup already in the script.  Then I will expand on it from here and setup different batch group of servers, and allow the user to choose what batch group to run from the one script instead of different script for each group.
Thanks Again for setting this up in the API wrapper, makes things allot easier   :-)
Mike Masters

**Comment by wcarroll** [comment]
Glad to hear it!
