### ISSUE TITLE
Start-ZertoFailoverTest errors with empty $body

### ISSUE THREAD

**Issue by kentgs** [ZertoPublic/ZertoApiWrapper#57]
## Expected Behavior
A ZertoFailoverTest begins.

## Current Behavior
After using 'Connect-ZertoServer' I am able to run other functions, but cannot start a failover test.  Specifying vpgName and/or vmName all results in failure.

Running 'Get-ZertoVpg -vpgName name' or 'Get-ZertoProtectedVm -vmName name' both succeed, while 'Start-ZertoFailoverTest -vpgName name' fails.

## Steps to Reproduce (for bugs)
After a successful 'Connect-ZertoServer':

PS H:\> Start-ZertoFailoverTest -vpgName "VPG_name"
Invoke-ZertoRestRequest : Cannot validate argument on parameter 'body'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\ZertoApiWrapper\1.2.0.20190801\ZertoApiWrapper.psm1:5304 char:68
+ ... oRestRequest -uri $uri -method "POST" -body $($body | ConvertTo-Json)
+                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ZertoRestRequest], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ZertoRestRequest

## Context

We would like to use this function to automate failover testing.

## Your Environment

* Module version used: 1.2.0.20190801
* Operating System and PowerShell version: Windows 2016 with PS 5 and 6, also Mac 10.14 with PS 6 and 7
* Zerto Virtual Manager Version: 7.5U1

**Comment by wcarroll** [comment]
Hi @kentgs  

Thanks for reporting this bug. I believe I know what the issue is and will be digging in. It is my intention to release an updated version of this wrapper in the next few days and should be able to get this fix in the next version that gets pushed to the PowerShell Gallery.

**Comment by wcarroll** [comment]
Hi @kentgs 

Just wanted to let you know that I have published this fix in the latest update that was pushed to the PowerShell Gallery today. You should be able to update the module and this should now work.

**Comment by kentgs** [comment]
Hi Wes - I've pulled the updated module and was able to run Start-ZertoFailoverTest successfully.  Thanks specifically for this fix, and more generally for working on this module.  Much appreciated!
