### ISSUE TITLE
Unable to Export Nic Settings

### ISSUE THREAD

**Issue by dbarkho** [ZertoPublic/ZertoApiWrapper#61]
## Expected Behavior
Run the Export-ZertoVmNicSetting against a single or all VPGs to export settings into a csv file which can then be edited for import.

## Current Behavior
When running the command, I am receiving an array index error as per below:

PS C:\Users\dbarkho> Export-ZertoVmNicSetting -VpgName "DanTest" -OutputFile E:\temp\export.csv
Index operation failed; the array index evaluated to null.
At C:\Program Files\WindowsPowerShell\Modules\ZertoApiWrapper\1.3.0.20191201\ZertoApiWrapper.psm1:597 char:53
+ ...                    VMName               = $vmMap[$($vm.vmIdentifier)]
+                                                        ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex

Export-Csv : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\ZertoApiWrapper\1.3.0.20191201\ZertoApiWrapper.psm1:621 char:24
+         $nicSettings | Export-Csv -Path $OutputFile
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-Csv], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ExportCsvCommand

## Steps to Reproduce (for bugs)

1. Connect to the ZVM: Connect-ZertoServer -zertoServer "<ZVM IP>"
2. Run the Nic export comand: Export-ZertoVmNicSetting -VpgName "DanTest" -OutputFile E:\temp\export.csv

The above error is then received. I have tried against a single or all VPGs, but no luck unfortunately. 

## Your Environment

* Module version used: 1.3.0.20191201
* Operating System and PowerShell version: Windows server 2k16, PS 5.1
* Zerto Virtual Manager Version: 7.0U1

**Comment by wcarroll** [comment]
Hi @dbarkho 

I tested this against a 7.5 Update 1 environment and was unable to reproduce. I want to test against a 7.0 Update 1 environment as I know some fixes and updates were made that could be impacting this function, but that is going to take a few days. In the mean time, can you please run the following command and let me know the outcome?

```PowerShell
Get-ZertoProtectedVm -vpgName "DanTest" | Select vmName, vmIdentifier
```

**Comment by dbarkho** [comment]
Hey Wes,

Thanks for getting back so quickly :) Love your work.

Below is the output of the above command:

PS C:\Users\dbarkho> Get-ZertoProtectedVm -vpgName "DanTest" | Select
vmName, vmIdentifier

VmName  VmIdentifier
------  ------------
DanTest ace4872c-78ab-4f85-80e8-e4b7138c1d7f.vm-1110444


Cheers.

**Comment by wcarroll** [comment]
Thanks! Glad to hear it. :) 

Thanks for getting me that information. It looks like the issue may be further down the stack, but unsure how to test easily. I'm going to be out of pocket the next few days, but will get a 7.0 Update 1 lab setup when I get a free minute. Once I am able to test against that version, I will let you know what I find and next steps.

**Comment by wcarroll** [comment]
Hi @dbarkho,
Can you validate for me that the VM you are testing with has a NIC attached to it? I only way I was able to reproduce this issue is when I removed all NICs from my test virtual machines.

**Comment by wcarroll** [comment]
I have updated the code base with logic that should correct the issue that you are running into. There are a few more updates that I would like to make before pushing the updated package to the PowerShell gallery around the first of the year. If you can't wait for the PowerShell gallery update, follow these instructions.

1. Use git to clone the repository.
2. Navigate to the local location.
3. In PowerShell, execute the `build.ps1` script. This will ensure that the required modules are installed on the local machine, and run through tests and automation to build the module.
4. After the build is completed, there will be a `temp` directory under the local repository. In that folder will be the module files along with the help directory. You can directly import the module from there and you will have the updated functions.

Thanks.

**Comment by dbarkho** [comment]
Thanks Wes! Sorry for the late reply. I will test it out when I get the
chance. Much appreciated :)
