### ISSUE TITLE
Implement logic if commitPolicyTimeout is Set, commitPolicy is Mandatory.

### ISSUE THREAD

**Issue by wcarroll** [ZertoPublic/ZertoApiWrapper#86]
https://github.com/ZertoPublic/ZertoApiWrapper/blob/73540faeb90e1461f3e4d489b1e415f2bbf890f0/ZertoApiWrapper/Public/Invoke-ZertoMove.ps1#L24-L24

**Comment by gdbarron** [comment]
Cool, glad you like the approach.  I'll try and walkthrough the steps.  Out of curiosity, why did you go with this approach for commenting as opposed to inline help?

**Comment by wcarroll** [comment]
External vs. comment based help was decision that I struggled with, but a decision that I had to make early on. I ended up deciding on the external approach to streamline the external documentation by leveraging the markdown files here on GitHub as an easy way to allow for online help as well as a method to quickly update the help files without having to understand powershell at all.

Looking back, it is a decision I'm not 100% happy with but going back to update each and every function is beyond daunting. If I ever need to do this again, I will evaluate comment based help again and see if the comment based help makes more sense then.

Would like to know your thoughts.

**Comment by gdbarron** [comment]
Your steps worked and I've initiated the PR.  Hopefully it looks good; let me know if there's anything else to be done.

As for the help, I've only ever used comment based help and extracted out with PlatyPS when I wanted to do something else with it.  You make a good point about not having to understand powershell at all, but I guess it's either you need to know PS comment based help or you need to know markdown.  Perhaps markdown is more universal and that makes your approach better.  Then again, other than perhaps very large corporations who have dedicated folks for documentation, PS devs are typically doing their own 😄 Not sure there's a 'right' answer, but I'll definitely give it some more thought.

**Comment by wcarroll** [comment]
@gdbarron Thanks for knocking this out. I am working on a couple of additional functions for VPG creation to Azure. Once I have those knocked out, I'll get this update published to the gallery. Have a great weekend.

Thanks,
WEs
